#!/usr/bin/env php

<?php

include "src/Dates/BirthDates.php";

$birthDate = "1976-07-24";

$days = new Prospero\Dates\BirthDates($birthDate);

$totalDays = $days->findTotalDays();

echo "$birthDate: $totalDays\n";

